"""Initial migration

Revision ID: 50799062151a
Revises: 
Create Date: 2024-09-02 11:52:34.381179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50799062151a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('village',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('subtitle', sa.String(length=128), nullable=True),
    sa.Column('advice', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('village', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_village_name'), ['name'], unique=True)

    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['village_id'], ['village.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_building_name'), ['name'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=False)

    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_deadline'), ['deadline'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_deadline'))

    op.drop_table('goal')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_name'))

    op.drop_table('project')
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_building_name'))

    op.drop_table('building')
    with op.batch_alter_table('village', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_village_name'))

    op.drop_table('village')
    # ### end Alembic commands ###
