"""Add archived field to Goal and List models

Revision ID: 7fdc1d904689
Revises: 8aecec5896f1
Create Date: 2024-09-04 07:02:43.803286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdc1d904689'
down_revision = '8aecec5896f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
