"""Add archived field to Project model

Revision ID: d05a043a70b2
Revises: 7fdc1d904689
Create Date: 2024-09-04 07:28:02.002068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05a043a70b2'
down_revision = '7fdc1d904689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
