"""Add List and ListItem models

Revision ID: f3075e916fe2
Revises: b68b6df57ee4
Create Date: 2024-09-03 17:19:37.013830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3075e916fe2'
down_revision = 'b68b6df57ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_name'), ['name'], unique=False)

    op.create_table('list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_item')
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_name'))

    op.drop_table('list')
    # ### end Alembic commands ###
